### ISSUE TITLE
hikvision-to-mqtt PHP file exits after a few seconds

### ISSUE THREAD

**Issue by famprinz** [zoilomora/hikvision-to-mqtt#3]
Hi - I'm new to Docker so it might be me. 

That being said, maybe you can help me figure out how to get this working. The hikvision-to-mqtt_php container does not start. The log says ': No such file or directory. Do you know how to fix this?

**Comment by zoilomora** [comment]
I just did the test following the [README.md](https://github.com/zoilomora/hikvision-to-mqtt/blob/master/README.md) and it worked for me without problems.

Could you attach a screenshot?

**Comment by famprinz** [comment]
That was quick ...  attached the screenshots 
![one](https://user-images.githubusercontent.com/67285329/92283126-8560b480-eeff-11ea-95d5-57093d7d09d6.PNG)
![two](https://user-images.githubusercontent.com/67285329/92283168-9ad5de80-eeff-11ea-91dc-237306dcea96.PNG)

**Comment by famprinz** [comment]
I downloaded the file and did "docker-compose up"
Maybe I didn't do it right (new to docker). The "make start" command didn't work and I never got into the shell. Hence, could be me not getting it...

**Comment by zoilomora** [comment]
@famprinz if I don't run the `make start` command it won't work.

The `make start` command, among other things, download the dependencies. It is possible that the error is indicating that it cannot find `autoload.php`.

You have to [download the dependencies](https://github.com/zoilomora/hikvision-to-mqtt/blob/master/Makefile#L18) before starting the docker container.

**Comment by famprinz** [comment]
Understood - I tried the make start but it keeps on telling me " 'make' is not recognized as an internal or external command,
operable program or batch file." - 

Thanks again for taking the time.

**Comment by zoilomora** [comment]
Can you give me more information about your environment?
* Operating system? (Windows or Linux) and Version?

`make` should be the default on any linux distribution.

**Comment by famprinz** [comment]
Sure

windows 10
Docker Desktop Version 2.3.0.4

**Comment by zoilomora** [comment]
I haven't used Windows with Docker in a long time.

Try running these commands (taken from the [Makefile](https://github.com/zoilomora/hikvision-to-mqtt/blob/master/Makefile)):
```
docker-compose down -v
docker-compose build
docker-compose pull
docker-compose run --rm php composer install
docker-compose run --rm php sh
```

**Note:** you may have to remove the volume mount from the `~/composer` folder [here](https://github.com/zoilomora/hikvision-to-mqtt/blob/master/docker-compose.yml#L11).

**Comment by famprinz** [comment]
Its runnung :-)

Will check the rest tomorrow when I got the NVR plugged in again

**Comment by famprinz** [comment]
THANKS!!

**Comment by zoilomora** [comment]
@famprinz close the issus if the problem is solved 😉

**Comment by famprinz** [comment]
Next challenge - never did that either. ... will do
